# API Linter Configuration
# https://linter.aip.dev/

- included_paths:
    - "**/*.proto"
  disabled_rules:
    - "core::0140::abbreviations"
    - "core::0191::java-multiple-files"
    - "core::0191::java-outer-classname"
    - "core::0191::java-package"
    - "core::0191::proto-package"
    - "core::0123::resource-annotation"
    - "core::0203::optional"
    - "core::0203::required"
    - "core::0127::http-annotation"
    - "core::0131::request-message-name"
    - "core::0132::response-message-name"
    - "core::0158::request-required-fields"
    - "core::0203::input-only"
    - "core::0203::output-only"
    - "core::0203::immutable"

    # TODO: Evaluate if the following should be enabled due to breaking changes
    - "core::0131::method-signature"
    - "core::0131::http-uri-name"
    - "core::0127::resource-name-extraction"
    - "core::0131::request-name-required"
    - "core::0131::request-required-fields"
    - "core::0131::response-message-name"
    - "core::0131::request-unknown-fields"
    - "core::0132::request-required-fields"
    - "core::0132::request-unknown-fields"
    - "core::0132::request-parent-required"
    - "core::0132::response-unknown-fields"
    - "core::0133::http-body"
    - "core::0133::request-required-fields"
    - "core::0133::request-unknown-fields"
    - "core::0133::request-parent-required"
    - "core::0133::request-resource-field"
    - "core::0133::request-id-field"
    - "core::0133::http-uri-parent"
    - "core::0135::http-uri-name"
    - "core::0135::request-name-required"
    - "core::0135::method-signature"
    - "core::0135::request-unknown-fields"
    - "core::0135::request-required-fields"
    - "core::0136::http-uri-suffix"
    - "core::0136::prepositions"
    - "core::0136::request-message-name"
    - "core::0136::response-message-name"
    - "core::0140::uri"
    - "core::0140::base64"
    - "core::0140::prepositions"
    - "core::0142::time-field-names"
    - "core::0191::file-layout"
    - "core::0203::field-behavior-required"
    - "core::0216::state-field-output-only"
    - "core::0216::nesting"
